from typing import Optional, List

from .collection import Collection


class Direct(Collection):

    def get_inbox(self, cursor_id: Optional[str] = None): ...

    def get_pending_inbox(self, cursor_id: Optional[str] = None): ...

    def approve_pending_threads(self, threads: list): ...

    def decline_pending_threads(self, threads: list): ...

    def decline_all_pending_threads(self): ...

    def get_presences(self): ...

    def get_ranked_recipients(self): ...

    def get_thread_by_participants(self, users: List[int]): ...

    def get_thread(self, thread_id: int, cursor_id: Optional[str] = None): ...

    def get_visual_thread(self, thread_id: int, cursor_id: Optional[str] = None): ...

    def update_thread_title(self, thread_id: int, title: str): ...

    def mute_thread(self, thread_id: int): ...

    def unmute_thread(self, thread_id: int): ...

    def create_group_thread(self, user_ids: List[int], thread_title: str): ...

    def add_users_to_thread(self, thread_id: int, users: List[int]): ...

    def leave_thread(self, thread_id: int): ...

    def hide_thread(self, thread_id: int): ...

    def send_text(self, recipients: list, text: str, options: dict = None): ...

    def send_post(self, recipients: list, media_id: int, options: dict = None): ...

    def send_photo(self, recipients: list, photo_filename: str, options: dict = None): ...

    def send_disappearing_photo(self, recipients: list, photo_filename: str, external_metadata: dict = None): ...

    def send_replayable_photo(self, recipients: list, photo_filename: str, external_metadata: dict = None): ...

    def send_video(self, recipients: list, video_filename: str, options: dict = None): ...

    def send_siappearing_video(self, recipients: list, video_filename: str, external_metadata: dict = None): ...

    def send_replayable_video(self, recipients: list, video_filename: str, external_metadata: dict = None): ...

    def send_like(self, recipients: list, options: dict = None): ...

    def send_hashtag(self, recipients: list, hashtag: str, options: dict = None): ...

    def send_location(self, recipients: list, location_id: int, options: dict = None): ...

    def send_profile(self, recipients: list, user_id: int, options: dict = None): ...

    def send_reaction(self, thread_id: int, thread_item_id: int, reaction_type: str, options: dict = None): ...

    def send_story(self, recipients: list, story_id: int, reel_id: int = None, options: dict = None): ...

    def send_live(self, recipients: list, broadcast_id: int, options: dict = None): ...

    def delete_reaction(self, thread_id: int, thread_item_id: int, reaction_type: str, options: dict = None): ...

    def delete_item(self, thread_id: int, thread_item_id: int): ...

    def mark_item_seen(self, thread_id: int, thread_item_id: int): ...

    def mark_visual_items_seen(self, thread_id: int, thread_item_ids: List[int]): ...

    def mark_visual_items_replayed(self, thread_id: int, thread_item_ids: List[int]): ...


