from typing import List

from .collection import Collection


class Media(Collection):

    def get_info(self, media_id: int): ...

    def delete(self, media_id: int, media_type='PHOTO'): ...

    def edit(self, media_id: int, caption_text: str = '', metadata: dict = None, media_type: str = 'PHOTO'): ...

    def like(self, media_id: int, module: str = 'feed_timeline', extra_data: dict = None): ...

    def unlike(self, media_id: int, module: str = 'feed_timeline', extra_data: dict = None): ...

    def get_liked_feed(self, max_id: str = None): ...

    def get_likers(self, media_id: int): ...

    def get_likers_group(self, media_id: int): ...

    def enable_comments(self, media_id: int): ...

    def disable_comments(self, media_id: int): ...

    def comment(self, media_id: int, comment_text: str, reply_comment_id: int = None, module: str = 'comments_v2'): ...

    def get_comments(self, media_id: int, options: dict = None): ...

    def get_comment_replies(self, media_id: int, comment_id: int, options: dict = None): ...

    def delete_comment(self, media_id: int, comment_id: int): ...

    def delete_comments(self, media_id: int, comment_ids: List[int]): ...

    def like_comment(self, comment_id: int): ...

    def unlike_comment(self, comment_id: int): ...

    def get_comment_likers(self, comment_id: int): ...

    def translate_comments(self, comment_ids: List[int]): ...

    def validate_url(self, url: str): ...

    def save(self, media_id: int): ...

    def unsave(self, media_id: int): ...

    def get_saved_feed(self, max_id: str = None): ...

    def get_blocked_media(self): ...

    def report(self, media_id: int, source_name: str = 'feed_contextual_chain'): ...

    def report_comment(self, media_id: int, comment_id: int): ...

    def get_permalink(self, media_id: int): ...


