from typing import List

from .base import CollectionBase


class People(CollectionBase):

    def get_info_by_id(self, user_id: int, module: str = None): ...

    def get_info_by_name(self, username: str, module: str = 'feed_timeline'): ...

    def get_user_id_for_name(self, username: str): ...

    def get_self_info(self): ...

    def get_recent_activity_inbox(self): ...

    def get_following_recent_activity(self, max_id: str = None): ...

    def get_bootstrap_users(self): ...

    def get_friendship(self, user_id: int): ...

    def get_friendships(self, user_list: List[int]): ...

    def get_pending_friendships(self): ...

    def approove_friendship(self, user_id: int): ...

    def reject_friendship(self, user_id: int): ...

    def remove_follower(self, user_id: int): ...

    def mark_user_overage(self, user_id: int): ...

    def get_following(self, user_id: int, rank_token: str, search_query: str = None, max_id: str = None): ...

    def get_followers(self, user_id: int, rank_token: str, search_query: str = None, max_id: str = None): ...

    def get_self_following(self, rank_token: str, search_query: str = None, max_id: str = None): ...

    def get_self_followers(self, rank_token: str, search_query: str = None, max_id: str = None): ...

    def search(self, query: str, exclude_list: List[int] = None, rank_token: str = None): ...

    def get_account_details(self, user_id: int): ...

    def get_former_usernames(self, user_id: int): ...

    def get_shared_followers(self, user_id: int): ...

    def get_active_feed_ads(self, target_user_id: int, max_id: str = None): ...

    def get_active_story_ads(self, target_user_id: int, max_id: str = None): ...

    def link_address_book(self, contacts: dict, module: str = 'find_friends_contacts'): ...

    def unlink_address_book(self): ...

    def discover_people(self, max_id: str = None): ...

    def get_suggested_users(self, user_id: int): ...

    def get_suggested_users_badge(self): ...

    def hide_suggested_user(self, user_id: int, algorithm: str): ...

    def follow(self, user_id: int): ...

    def unfollow(self, user_id: int): ...

    def favorite(self, user_id: int): ...

    def unfavorite(self, user_id: int): ...

    def favorite_for_stories(self, user_id: int): ...

    def unfavorite_for_stories(self, user_id: int): ...

    def report(self, user_id: int, source_name: str = 'profile'): ...

    def block(self, user_id: int): ...

    def mute_user_media(self, user_id: int, option: str): ...

    def unmute_user_media(self, user_id: int, option: str): ...

    def unblock(self, user_id: int): ...

    def get_blocked_list(self, max_id: str = None): ...

    def block_my_story(self, user_id: int): ...

    def unblock_my_story(self, user_id: int): ...

    def get_blocked_story_list(self): ...

    def mute_friend_story(self, user_id: int): ...

    def unmute_friend_story(self, user_id: int): ...

    def get_close_friends(self): ...

    def get_suggested_close_friends(self): ...

    def set_close_friends(self,
                          add: List[int],
                          remove: List[int],
                          module: str = 'favorites_home_list',
                          source: str = 'audience_manager'): ...
