from typing import List

from instagram_api.response.model.item import Item
from .base import CollectionBase


class Story(CollectionBase):

    def upload_photo(self, photo_filename: str, external_metadata: dict = None): ...

    def upload_close_friends_photo(self, photo_filename: str, external_metadata: dict = None): ...

    def upload_video(self, video_filename: str, external_metadata: dict = None): ...

    def upload_close_friends_video(self, video_filename: str, external_metadata: dict = None): ...

    def get_reels_tray_feed(self): ...

    def get_user_reel_media_feed(self, user_id: int): ...

    def get_user_story_feed(self, user_id: int): ...

    def get_reels_media_feed(self, feed_list: List[int], source: str = 'feed_timeline'): ...

    def get_archived_stories_feed(self): ...

    def get_story_item_viewers(self, story_pk: int, max_id: str = None): ...

    def vote_poll_story(self, story_id: int, poll_id: int, voting_option: int): ...

    def vote_slider_story(self, story_id: int, slider_id: int, voting_option: int): ...

    def get_story_poll_voters(self, story_id: int, poll_id: int, voting_option: int, max_id: str = None): ...

    def answer_story_question(self, story_id: int, question_id: int, response_text: str): ...

    def get_story_answers(self, story_id: int, question_id: int, max_id: str = None): ...

    def get_story_countdowns(self): ...

    def follow_story_countdown(self, countdown_id: int): ...

    def unfollow_story_countdown(self, countdown_id: int): ...

    def mark_media_seen(self, items: List[Item]): ...

    def get_reel_settings(self): ...

    def set_reel_settings(self, message_prefs: str, allow_story_reshare: bool = None, auto_archive: str = None): ...


