from instagram_api import response

from .base import CollectionBase

__all__ = ['Timeline']


class Timeline(CollectionBase):

    def upload_photo(self, photo_filename: str, external_metadata: dict = None) -> response.ConfigureResponse: ...

    def upload_video(self, video_filename: str, external_metadata: dict = None) -> response.ConfigureResponse: ...

    def upload_album(self, medai: dict, external_metadata: dict = None) -> response.ConfigureResponse: ...

    def get_timeline_feed(self, max_id: str = None, options: dict = None) -> response.TimelineFeedResponse: ...

    def get_user_feed(self, user_id: int, max_id: str = None) -> response.UserFeedResponse: ...

    def get_self_user_feed(self, max_id: str = None) -> response.UserFeedResponse: ...

    def get_archived_media_feed(self) -> response.UserFeedResponse: ...

    def archive_media(self, media_id: int, only_me: bool = True) -> response.ArchiveMediaResponse: ...

    def backup(self, base_output_path: str = None, print_progress: bool = True): ...
