from .base import CollectionBase


class Timeline(CollectionBase):

    def upload_photo(self, photo_filename: str, external_metadata: dict = None): ...

    def upload_video(self, video_filename: str, external_metadata: dict = None): ...

    def upload_album(self, medai: dict, external_metadata: dict = None): ...

    def get_timeline_feed(self, max_id: str = None, options: dict = None): ...

    def get_user_feed(self, user_id: int, max_id: str = None): ...

    def get_self_user_feed(self, max_id: str = None): ...

    def get_archived_media_feed(self): ...

    def archive_media(self, media_id: int, only_me: bool = True): ...

    def backup(self, base_output_path: str = None, print_progress: bool = True): ...


